### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hancockp-at-ibm** [ibm-cloud-docs/hs-crypto#31] opened 2022-04-05 10:33 UTC
In https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-master-key-rotation-intro 
the link in this sentence 
`For detailed instructions, see [Rotating master keys by using key parts](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-rotate-master-key-key-parts).`

is broken.

**Comment by TiffanyLiIBM** [comment] 2022-04-06 07:35
Hi @hancockp-at-ibm,

Please find the updated doc at: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm#initialize-crypto-cli-next.
The link has been fixed to point to: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-rotate-master-key-cli-key-part. Please close this issue if the problem is resolved. Thanks!

**Comment by TiffanyLiIBM** [comment] 2022-05-11 05:33
No more comments received. Closing...

**Closed as completed by TiffanyLiIBM** 2022-05-11 05:33 UTC

**Comment by hancockp-at-ibm** [comment] 2022-05-11 09:50
@TiffanyLiIBM, Thank you. For some reason, I didn't get (or notice?) the notification about your earlier reply.
